image: node:24

stages:
  - build

create-pages:
  stage: build
  before_script:
    - corepack enable
    - pnpm config set store-dir .pnpm-store
    - pnpm install --frozen-lockfile
  script:
    - pnpm lint
    - pnpm test:unit
    - pnpm build
  pages:
    publish: dist
  artifacts:
    paths:
      - dist
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
