workflow:
  auto_cancel:
    on_new_commit: interruptible
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

stages:
  - lint
  - test
  - release

.node_base: &node_base
  image: node:24.19.0
  before_script:
    - npm install --global corepack@latest
    - corepack enable
    - pnpm config set store-dir .pnpm-store
    - pnpm install --frozen-lockfile
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

lint:
  <<: [*node_base]
  stage: lint
  interruptible: true
  script:
    - pnpm lint

test:
  <<: [*node_base]
  stage: test
  interruptible: true
  script:
    - pnpm test:unit

pages:
  <<: [*node_base]
  stage: release
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$/'
  script:
    - pnpm build
  pages:
    publish: dist
  artifacts:
    paths:
      - dist
